import { Dimensions, StyleSheet } from "react-native";

const { width, height } = Dimensions.get("window");
const headerHeight = Math.min(330, Math.max(250, height * 0.38));

export const COLORS = {
  background: "#F7FAF5",
  primary: "#14613C",
  dark: "#082A1A",
  accent: "#2D8A5C",
  softGreen: "#EAF4EE",
  gold: "#C9A646",
  softGold: "#F0D98A",
  white: "#FFFFFF",
  text: "#17251D",
  muted: "#68746D",
  border: "#C8D4CC",
  input: "#FFFFFF",
  danger: "#B91C1C",
  placeholder: "#9AA59E",
};

export default StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: COLORS.primary,
  },
  keyboard: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
    backgroundColor: COLORS.primary,
  },
  scrollContent: {
    flexGrow: 1,
    backgroundColor: COLORS.primary,
  },
  header: {
    minHeight: headerHeight,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 22,
    paddingBottom: 46,
    paddingHorizontal: 34,
    overflow: "hidden",
  },
  headerPattern: {
    ...StyleSheet.absoluteFillObject,
  },
  headerGlow: {
    position: "absolute",
    width: width + 90,
    height: headerHeight,
    left: -46,
    top: -28,
    backgroundColor: "rgba(8,42,26,0.28)",
    borderBottomLeftRadius: 180,
    borderBottomRightRadius: 180,
  },
  headerCircleTop: {
    position: "absolute",
    width: 48,
    height: 48,
    borderRadius: 24,
    right: 70,
    top: 36,
    backgroundColor: "rgba(201,166,70,0.35)",
  },
  headerCircleLeft: {
    position: "absolute",
    width: 108,
    height: 108,
    borderRadius: 54,
    left: -48,
    top: 34,
    backgroundColor: "rgba(45,138,92,0.52)",
  },
  headerCircleRight: {
    position: "absolute",
    width: 82,
    height: 82,
    borderRadius: 41,
    right: -18,
    bottom: 16,
    backgroundColor: "rgba(8,42,26,0.44)",
  },
  headerGoldDot: {
    position: "absolute",
    width: 12,
    height: 12,
    borderRadius: 6,
    right: 36,
    top: 86,
    backgroundColor: COLORS.softGold,
  },
  logo: {
    width: Math.min(width * 0.78, 300),
    height: Math.min(width * 0.38, 148),
    marginBottom: 4,
  },
  headerTitle: {
    color: COLORS.white,
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "900",
    letterSpacing: 0,
    textAlign: "center",
  },
  headerSubtitle: {
    color: "rgba(255,255,255,0.84)",
    fontSize: 11,
    lineHeight: 16,
    fontWeight: "700",
    letterSpacing: 0,
    textAlign: "center",
    marginTop: 5,
  },
  panel: {
    width: "100%",
    alignSelf: "center",
    flex: 1,
    marginTop: -28,
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingTop: 34,
    paddingBottom: 36,
    shadowColor: COLORS.dark,
    shadowOpacity: 0.06,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: -2 },
    elevation: 5,
  },
  panelContent: {
    width: width - 34,
    alignSelf: "center",
    flex: 1,
  },
  fieldGroup: {
    width: "100%",
    marginBottom: 14,
  },
  fieldLabel: {
    color: COLORS.dark,
    fontSize: 11,
    fontWeight: "800",
    marginBottom: 5,
  },
  inputField: {
    width: "100%",
    height: 42,
    borderRadius: 8,
    borderWidth: 1,
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    color: COLORS.text,
    fontSize: 12,
    fontWeight: "700",
    paddingHorizontal: 14,
    paddingTop: 0,
    paddingBottom: 0,
  },
  inputFieldFocused: {
    borderColor: COLORS.gold,
    shadowColor: COLORS.gold,
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  passwordWrap: {
    position: "relative",
  },
  passwordField: {
    paddingRight: 42,
  },
  eyeButton: {
    position: "absolute",
    right: 6,
    top: 4,
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  optionsRow: {
    width: "100%",
    minHeight: 32,
    marginTop: 0,
    marginBottom: 22,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  staySignedInButton: {
    minHeight: 32,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  staySignedInText: {
    color: COLORS.muted,
    fontSize: 10,
    fontWeight: "700",
  },
  linkText: {
    color: COLORS.text,
    fontSize: 10,
    fontWeight: "800",
    textDecorationLine: "underline",
  },
  errorBox: {
    width: "100%",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    backgroundColor: "#FEF2F2",
    borderWidth: 1,
    borderColor: "#FECACA",
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 14,
  },
  errorText: {
    flex: 1,
    color: COLORS.danger,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "800",
  },
  loginButton: {
    width: "88%",
    minHeight: 46,
    borderRadius: 8,
    backgroundColor: COLORS.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    gap: 8,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.28,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 5 },
    elevation: 5,
    borderWidth: 1,
    borderColor: "rgba(201,166,70,0.55)",
  },
  loginButtonDisabled: {
    opacity: 0.72,
    shadowOpacity: 0,
    elevation: 0,
  },
  loginButtonText: {
    color: COLORS.white,
    fontSize: 15,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  registerText: {
    marginTop: 34,
    color: COLORS.text,
    fontSize: 11,
    lineHeight: 17,
    fontWeight: "700",
    textAlign: "right",
  },
  registerLink: {
    color: COLORS.primary,
    fontWeight: "900",
  },
});
