import { Platform, StyleSheet } from "react-native";

export const COLORS = {
  bg: "#F2F7F3",
  surface: "#FFFFFF",
  surfaceSoft: "#F7FBF7",
  text: "#10251B",
  textMuted: "#647067",
  green: "#14532D",
  greenDeep: "#355A2C",
  greenSoft: "#E7F4EA",
  border: "#DFE9E1",
  placeholder: "#94A3B8",
  danger: "#DC2626",
};

export const METRICS = {
  phoneMaxWidth: 430,
  padH: 18,
  padTop: 34,
  inputH: 50,
  btnH: 52,
};

const styles = StyleSheet.create({
  webFrame: {
    flex: 1,
    alignItems: "center",
    backgroundColor: Platform.OS === "web" ? "#EAF0EA" : COLORS.bg,
  },
  phone: {
    flex: 1,
    width: "100%",
    maxWidth: METRICS.phoneMaxWidth,
    backgroundColor: COLORS.bg,
  },
  scrollContent: {
    paddingHorizontal: METRICS.padH,
    paddingTop: METRICS.padTop,
    paddingBottom: Platform.OS === "android" ? 42 : 30,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 18,
  },
  backBtn: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  headerCopy: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: COLORS.text,
  },
  subText: {
    marginTop: 3,
    fontSize: 12,
    color: COLORS.textMuted,
    fontWeight: "600",
    lineHeight: 17,
  },
  securityHero: {
    flexDirection: "row",
    alignItems: "center",
    padding: 18,
    borderRadius: 24,
    backgroundColor: COLORS.greenDeep,
    marginBottom: 14,
    shadowColor: "#16311E",
    shadowOpacity: 0.14,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  heroIcon: {
    width: 56,
    height: 56,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.14)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 13,
  },
  heroCopy: {
    flex: 1,
  },
  heroTitle: {
    color: "#FFFFFF",
    fontSize: 17,
    fontWeight: "900",
  },
  heroText: {
    marginTop: 4,
    color: "rgba(255,255,255,0.8)",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "600",
  },
  sectionCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 22,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: "#0F2319",
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "900",
    color: COLORS.text,
  },
  inputWrap: {
    marginTop: 14,
  },
  inputLabel: {
    marginBottom: 7,
    color: COLORS.text,
    fontSize: 12,
    fontWeight: "900",
  },
  input: {
    width: "100%",
    minHeight: METRICS.inputH,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 16,
    paddingHorizontal: 14,
    color: COLORS.text,
    backgroundColor: "#FBFDFC",
    fontSize: 15,
  },
  error: {
    color: COLORS.danger,
    marginTop: 8,
    fontSize: 12,
    fontWeight: "700",
  },
  ruleGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 16,
  },
  rulePill: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "#F4F7F4",
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  rulePillOk: {
    backgroundColor: COLORS.greenSoft,
    borderColor: "#BFE2C6",
  },
  ruleText: {
    marginLeft: 5,
    color: COLORS.textMuted,
    fontSize: 11,
    fontWeight: "800",
  },
  ruleTextOk: {
    color: "#166534",
  },
  button: {
    width: "100%",
    height: METRICS.btnH,
    backgroundColor: COLORS.green,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
    shadowColor: COLORS.green,
    shadowOpacity: 0.16,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  buttonText: {
    color: "#FFFFFF",
    fontWeight: "900",
    fontSize: 15,
  },
  twoFAWrapper: {
    marginTop: 14,
    backgroundColor: COLORS.surface,
    borderRadius: 22,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: "#0F2319",
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  twoFATop: {
    flexDirection: "row",
    alignItems: "center",
  },
  twoFAIcon: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: COLORS.greenSoft,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  twoFACopy: {
    flex: 1,
    marginRight: 8,
  },
  subInfo: {
    marginTop: 4,
    fontSize: 12,
    color: COLORS.textMuted,
    fontWeight: "600",
    lineHeight: 17,
  },
  status: {
    alignSelf: "flex-start",
    marginTop: 14,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "#F1F5F1",
    color: "#55635B",
    fontSize: 12,
    fontWeight: "900",
    overflow: "hidden",
  },
  statusEnabled: {
    backgroundColor: "#DCF3E0",
    color: "#166534",
  },
});

export default styles;
