import { Platform, StyleSheet } from "react-native";

export const COLORS = {
  bg: "#F2F7F3",
  surface: "#FFFFFF",
  surfaceSoft: "#F7FBF7",
  text: "#10251B",
  textMuted: "#647067",
  green: "#14532D",
  greenDeep: "#355A2C",
  greenSoft: "#E7F4EA",
  border: "#DFE9E1",
  placeholder: "#94A3B8",
  danger: "#DC2626",
};

export const METRICS = {
  phoneMaxWidth: 430,
  padH: 18,
  padTop: 34,
  inputH: 50,
  btnH: 52,
};

const styles = StyleSheet.create({
  webFrame: {
    flex: 1,
    alignItems: "center",
    backgroundColor: Platform.OS === "web" ? "#EAF0EA" : COLORS.bg,
  },
  phone: {
    flex: 1,
    width: "100%",
    maxWidth: METRICS.phoneMaxWidth,
    backgroundColor: COLORS.bg,
  },
  scrollContent: {
    paddingHorizontal: METRICS.padH,
    paddingTop: METRICS.padTop,
    paddingBottom: Platform.OS === "android" ? 42 : 30,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 18,
  },
  backBtn: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  headerCopy: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: COLORS.text,
  },
  subText: {
    marginTop: 3,
    fontSize: 12,
    color: COLORS.textMuted,
    fontWeight: "600",
    lineHeight: 17,
  },
  summaryCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: 18,
    borderRadius: 24,
    backgroundColor: COLORS.greenDeep,
    marginBottom: 14,
    shadowColor: "#16311E",
    shadowOpacity: 0.14,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  summaryIcon: {
    width: 50,
    height: 50,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.14)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  summaryCopy: {
    flex: 1,
    minWidth: 0,
  },
  summaryTitle: {
    color: "#FFFFFF",
    fontSize: 17,
    fontWeight: "900",
  },
  summaryMeta: {
    marginTop: 4,
    color: "rgba(255,255,255,0.8)",
    fontSize: 12,
    fontWeight: "600",
  },
  sectionCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 22,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginTop: 14,
    shadowColor: "#0F2319",
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  sectionTitle: {
    color: COLORS.text,
    fontSize: 15,
    fontWeight: "900",
    marginBottom: 14,
  },
  readOnlyField: {
    minHeight: 56,
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surfaceSoft,
    paddingHorizontal: 14,
    marginBottom: 10,
  },
  readOnlyLabel: {
    width: 92,
    color: COLORS.textMuted,
    fontSize: 12,
    fontWeight: "800",
  },
  readOnlyValue: {
    flex: 1,
    color: COLORS.text,
    fontSize: 14,
    fontWeight: "800",
    marginRight: 8,
  },
  label: {
    fontSize: 13,
    fontWeight: "900",
    color: COLORS.text,
    marginBottom: 4,
  },
  helper: {
    fontSize: 12,
    color: COLORS.textMuted,
    marginBottom: 8,
    lineHeight: 18,
    fontWeight: "600",
  },
  input: {
    width: "100%",
    minHeight: METRICS.inputH,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 16,
    paddingHorizontal: 14,
    color: COLORS.text,
    backgroundColor: "#FBFDFC",
    fontSize: 15,
    marginBottom: 14,
  },
  button: {
    width: "100%",
    height: METRICS.btnH,
    backgroundColor: COLORS.green,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
    shadowColor: COLORS.green,
    shadowOpacity: 0.16,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  buttonText: {
    color: "#FFFFFF",
    fontWeight: "900",
    fontSize: 15,
  },
  error: {
    color: COLORS.danger,
    marginTop: -2,
    marginBottom: 10,
    fontSize: 12,
    fontWeight: "700",
  },
});

export default styles;
